name: running_creature_go
description: "A new Flutter project."
publish_to: "none"

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf
        - asset: fonts/Pretendard-Italic.ttf
          style: italic
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Bold.ttf
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 700
